CREATE OR REPLACE FUNCTION FNC0101_001_NUMBERING_PRACTICE_NO RETURN VARCHAR2 AS
SEQ VARCHAR2(13 CHAR);
BEGIN
  SELECT SQ0101_PRACTICE_NO.NEXTVAL INTO SEQ FROM DUAL;
  RETURN 'PR' || TO_CHAR(SYSDATE,'YYMMDD') || LPAD(SEQ,5,'0');
END;
  