DROP TABLE MH0001_INITIAL_CD;

CREATE TABLE MH0001_INITIAL_CD (
BUNRUI_CD VARCHAR2(5 CHAR) NOT NULL, 
BUNRUI_NAME VARCHAR2(1000 CHAR), 
KUBUN_CD VARCHAR2(5 CHAR) NOT NULL, 
KUBUN_NAME VARCHAR2(1000 CHAR), 
KUBUN_BETSU_NAME1 VARCHAR2(1000 CHAR), 
KUBUN_BETSU_NAME2 VARCHAR2(1000 CHAR), 
KUBUN_BETSU_NAME3 VARCHAR2(1000 CHAR), 
PARENT_CD CHAR(5 CHAR), 
CONSTANT_NAME VARCHAR2(1000 CHAR) NOT NULL UNIQUE,
RONRI_SAKUJO_FLG CHAR(1 CHAR) NOT NULL, 
CREATE_DATE DATE NOT NULL, 
CREATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
UPDATE_DATE DATE NOT NULL, 
UPDATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
CONSTRAINT MH0001_INITIAL_CD_PK PRIMARY KEY (BUNRUI_CD, KUBUN_CODE)
);

COMMENT ON TABLE MH0001_INITIAL_CD IS '初期コードマスタ';
COMMENT ON COLUMN MH0001_INITIAL_CD.BUNRUI_CD IS '分類コード';
COMMENT ON COLUMN MH0001_INITIAL_CD.BUNRUI_NAME IS '分類名';
COMMENT ON COLUMN MH0001_INITIAL_CD.KUBUN_CD IS '区分コード';
COMMENT ON COLUMN MH0001_INITIAL_CD.KUBUN_NAME IS '区分名';
COMMENT ON COLUMN MH0001_INITIAL_CD.KUBUN_BETSU_NAME1 IS '区分別名１';
COMMENT ON COLUMN MH0001_INITIAL_CD.KUBUN_BETSU_NAME2 IS '区分別名２';
COMMENT ON COLUMN MH0001_INITIAL_CD.KUBUN_BETSU_NAME3 IS '区分別名３';
COMMENT ON COLUMN MH0001_INITIAL_CD.PARENT_CD IS '親コード';
COMMENT ON COLUMN MH0001_INITIAL_CD.CONSTANT_NAME IS '定数名';
COMMENT ON COLUMN MH0001_INITIAL_CD.RONRI_SAKUJO_FLG IS '論理削除フラグ';
COMMENT ON COLUMN MH0001_INITIAL_CD.CREATE_DATE IS '作成日時';
COMMENT ON COLUMN MH0001_INITIAL_CD.CREATE_USER_CD IS '作成ユーザコード';
COMMENT ON COLUMN MH0001_INITIAL_CD.UPDATE_DATE IS '更新日時';
COMMENT ON COLUMN MH0001_INITIAL_CD.UPDATE_USER_CD IS '更新ユーザコード';
