DROP TABLE MH0002_AUTHORITY_MNG;

CREATE TABLE MH0002_AUTHORITY_MNG (
AUTH_CD VARCHAR2(20 CHAR) NOT NULL, 
RONRI_SAKUJO_FLG CHAR(1 CHAR) NOT NULL, 
CREATE_DATE DATE NOT NULL, 
CREATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
UPDATE_DATE DATE NOT NULL, 
UPDATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
CONSTRAINT MH0002_AUTHORITY_MNG_PK PRIMARY KEY (AUTH_CD)
);

COMMENT ON TABLE MH002_ROLE IS 'ロール';
COMMENT ON COLUMN MH002_ROLE.AUTH_CD IS '権限コード';
COMMENT ON COLUMN MH002_ROLE.RONRI_SAKUJO_FLG IS '論理削除フラグ';
COMMENT ON COLUMN MH002_ROLE.CREATE_DATE IS '作成日時';
COMMENT ON COLUMN MH002_ROLE.CREATE_USER_CD IS '作成ユーザコード';
COMMENT ON COLUMN MH002_ROLE.UPDATE_DATE IS '更新日時';
COMMENT ON COLUMN MH002_ROLE.UPDATE_USER_CD IS '更新ユーザコード';
