DROP TABLE TH0002_USER_DETAIL;

CREATE TABLE TH0002_USER_DETAIL (
USER_CD CHAR(5 CHAR) NOT NULL, 
USER_NAME_KANJI_SEI VARCHAR2(10 CHAR) NOT NULL,
USER_NAME_KANJI_MEI VARCHAR2(20 CHAR) NOT NULL,
USER_NAME_KANA_SEI VARCHAR2(50 CHAR) NOT NULL,
USER_NAME_KANA_MEI VARCHAR2(50 CHAR) NOT NULL,
TELL_NUM VARCHAR2(20 CHAR) NOT NULL,
POSTAL_NUM VARCHAR2(7 CHAR) NOT NULL,
ADDRESS VARCHAR2(200 CHAR) NOT NULL, 
MAIL_ADDRESS VARCHAR2(200 CHAR) NOT NULL, 
RONRI_SAKUJO_FLG CHAR(1 CHAR) NOT NULL, 
CREATE_DATE DATE NOT NULL, 
CREATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
UPDATE_DATE DATE NOT NULL, 
UPDATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
CONSTRAINT TH0002_USER_DETAIL_PK PRIMARY KEY (USER_CD)
);

COMMENT ON TABLE TH0002_USER_DETAIL IS 'ユーザ詳細';
COMMENT ON COLUMN TH0002_USER_DETAIL.USER_CD IS 'ユーザコード';
COMMENT ON COLUMN TH0002_USER_DETAIL.USER_NAME_KANJI_SEI IS 'ユーザ名漢字（姓）';
COMMENT ON COLUMN TH0002_USER_DETAIL.USER_NAME_KANJI_MEI IS 'ユーザ名漢字（名）';
COMMENT ON COLUMN TH0002_USER_DETAIL.USER_NAME_KANA_SEI IS 'ユーザ名カナ（姓）';
COMMENT ON COLUMN TH0002_USER_DETAIL.USER_NAME_KANA_MEI IS 'ユーザ名カナ（名）';
COMMENT ON COLUMN TH0002_USER_DETAIL.TELL_NUM IS '電話番号';
COMMENT ON COLUMN TH0002_USER_DETAIL.POSTAL_NUM IS '郵便番号';
COMMENT ON COLUMN TH0002_USER_DETAIL.ADDRESS IS '住所';
COMMENT ON COLUMN TH0002_USER_DETAIL.MAIL_ADDRESS IS 'メールアドレス';
COMMENT ON COLUMN TH0002_USER_DETAIL.RONRI_SAKUJO_FLG IS '論理削除フラグ';
COMMENT ON COLUMN TH0002_USER_DETAIL.CREATE_DATE IS '作成日時';
COMMENT ON COLUMN TH0002_USER_DETAIL.CREATE_USER_CD IS '作成ユーザコード';
COMMENT ON COLUMN TH0002_USER_DETAIL.UPDATE_DATE IS '更新日時';
COMMENT ON COLUMN TH0002_USER_DETAIL.UPDATE_USER_CD IS '更新ユーザコード';
