DROP TABLE TH0003_PASSWORD_HISTORY;

CREATE TABLE TH0003_PASSWORD_HISTORY (
USER_CD CHAR(5 CHAR) NOT NULL, 
USE_FROM DATE NOT NULL, 
PASSWORD VARCHAR2(1000 CHAR) NOT NULL, 
RONRI_SAKUJO_FLG CHAR(1 CHAR) NOT NULL, 
CREATE_DATE DATE NOT NULL, 
CREATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
UPDATE_DATE DATE NOT NULL, 
UPDATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
CONSTRAINT TH0003_PASSWORD_HISTORY_PK PRIMARY KEY (USER_CD,USE_FROM)
);

COMMENT ON TABLE TH0003_PASSWORD_HISTORY IS 'パスワード履歴';
COMMENT ON COLUMN TH0003_PASSWORD_HISTORY.USER_CD IS 'ユーザコード';
COMMENT ON COLUMN TH0003_PASSWORD_HISTORY.USE_FROM IS '使用開始日時';
COMMENT ON COLUMN TH0003_PASSWORD_HISTORY.PASSWORD IS 'パスワード';
COMMENT ON COLUMN TH0003_PASSWORD_HISTORY.RONRI_SAKUJO_FLG IS '論理削除フラグ';
COMMENT ON COLUMN TH0003_PASSWORD_HISTORY.CREATE_DATE IS '作成日時';
COMMENT ON COLUMN TH0003_PASSWORD_HISTORY.CREATE_USER_CD IS '作成ユーザコード';
COMMENT ON COLUMN TH0003_PASSWORD_HISTORY.UPDATE_DATE IS '更新日時';
COMMENT ON COLUMN TH0003_PASSWORD_HISTORY.UPDATE_USER_CD IS '更新ユーザコード';
