DROP TABLE TH0001_USER_ACCOUNT;

CREATE TABLE TH0001_USER_ACCOUNT (
USER_CD CHAR(5 CHAR) NOT NULL, 
PASSWORD VARCHAR2(1000 CHAR) NOT NULL, 
AUTH_CD VARCHAR2(20 CHAR) NOT NULL, 
LAST_LOGIN_DATE DATE NOT NULL, 
LOGIN_FAILED_CNT NUMBER(1) NOT NULL, 
RONRI_SAKUJO_FLG CHAR(1 CHAR) NOT NULL, 
CREATE_DATE DATE NOT NULL, 
CREATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
UPDATE_DATE DATE NOT NULL, 
UPDATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
CONSTRAINT TH0001_USER_ACCOUNT_PK PRIMARY KEY (USER_CD)
);

COMMENT ON TABLE TH0001_USER_ACCOUNT IS 'ユーザアカウント';
COMMENT ON COLUMN TH0001_USER_ACCOUNT.USER_CD IS 'ユーザコード';
COMMENT ON COLUMN TH0001_USER_ACCOUNT.PASSWORD IS 'パスワード';
COMMENT ON COLUMN TH0001_USER_ACCOUNT.AUTH_CD IS '権限コード';
COMMENT ON COLUMN TH0001_USER_ACCOUNT.LAST_LOGIN_DATE IS '最終ログイン日時';
COMMENT ON COLUMN TH0001_USER_ACCOUNT.LOGIN_FAILED_CNT IS 'ログイン失敗回数';
COMMENT ON COLUMN TH0001_USER_ACCOUNT.RONRI_SAKUJO_FLG IS '論理削除フラグ';
COMMENT ON COLUMN TH0001_USER_ACCOUNT.CREATE_DATE IS '作成日時';
COMMENT ON COLUMN TH0001_USER_ACCOUNT.CREATE_USER_CD IS '作成ユーザコード';
COMMENT ON COLUMN TH0001_USER_ACCOUNT.UPDATE_DATE IS '更新日時';
COMMENT ON COLUMN TH0001_USER_ACCOUNT.UPDATE_USER_CD IS '更新ユーザコード';
