DROP TABLE TH0102_PRACTICE_MODULE;

CREATE TABLE TH0102_PRACTICE_MODULE (
PRACTICE_MNG_NO CHAR(13 CHAR) NOT NULL, 
MODULE_NO　NUMBER(2,0) NOT NULL, 
MODULE_OVERVIEW VARCHAR2(100 CHAR), 
MODULE_NAME VARCHAR2(200 CHAR), 
MODULE BLOB, 
VERSION　NUMBER(9,0) NOT NULL, 
RONRI_SAKUJO_FLG CHAR(1 CHAR) NOT NULL, 
CREATE_DATE DATE NOT NULL, 
CREATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
UPDATE_DATE DATE NOT NULL, 
UPDATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
CONSTRAINT TH0102_PRACTICE_MODULE_PK PRIMARY KEY (PRACTICE_MNG_NO,MODULE_NO)
);

COMMENT ON TABLE TH0102_PRACTICE_MODULE IS 'サンプルモジュール';
COMMENT ON COLUMN TH0102_PRACTICE_MODULE.PRACTICE_MNG_NO IS 'サンプル管理番号';
COMMENT ON COLUMN TH0102_PRACTICE_MODULE.MODULE_NO IS 'モジュール番号';
COMMENT ON COLUMN TH0102_PRACTICE_MODULE.MODULE_OVERVIEW IS 'モジュール概要';
COMMENT ON COLUMN TH0102_PRACTICE_MODULE.MODULE_NAME IS 'モジュール名';
COMMENT ON COLUMN TH0102_PRACTICE_MODULE.MODULE IS 'モジュール';
COMMENT ON COLUMN TH0102_PRACTICE_MODULE.VERSION IS 'バージョン';
COMMENT ON COLUMN TH0102_PRACTICE_MODULE.RONRI_SAKUJO_FLG IS '論理削除フラグ';
COMMENT ON COLUMN TH0102_PRACTICE_MODULE.CREATE_DATE IS '作成日時';
COMMENT ON COLUMN TH0102_PRACTICE_MODULE.CREATE_USER_CD IS '作成ユーザコード';
COMMENT ON COLUMN TH0102_PRACTICE_MODULE.UPDATE_DATE IS '更新日時';
COMMENT ON COLUMN TH0102_PRACTICE_MODULE.UPDATE_USER_CD IS '更新ユーザコード';
