DROP TABLE TH0101_PRACTICE_MNG;

CREATE TABLE TH0101_PRACTICE_MNG (
PRACTICE_MNG_NO CHAR(13 CHAR) NOT NULL, 
OVERVIEW VARCHAR2(100 CHAR) NOT NULL,
CATEGORY　CHAR(2 CHAR), 
DETAIL VARCHAR2(1000 CHAR),
MEMO VARCHAR2(1000 CHAR),
VERSION　NUMBER(9,0) NOT NULL, 
RONRI_SAKUJO_FLG CHAR(1 CHAR) NOT NULL ENABLE, 
CREATE_DATE DATE NOT NULL ENABLE, 
CREATE_USER_CD VARCHAR2(50 CHAR) NOT NULL ENABLE, 
UPDATE_DATE DATE NOT NULL ENABLE, 
UPDATE_USER_CD VARCHAR2(50 CHAR) NOT NULL ENABLE, 
CONSTRAINT TH0101_PRACTICE_MNG_PK PRIMARY KEY (PRACTICE_MNG_NO)
);

COMMENT ON TABLE TH0101_PRACTICE_MNG IS 'サンプル管理';
COMMENT ON COLUMN TH0101_PRACTICE_MNG.PRACTICE_MNG_NO IS 'サンプル管理番号';
COMMENT ON COLUMN TH0101_PRACTICE_MNG.CATEGORY IS 'カテゴリ';
COMMENT ON COLUMN TH0101_PRACTICE_MNG.DETAIL IS '詳細';
COMMENT ON COLUMN TH0101_PRACTICE_MNG.MEMO IS 'メモ';
COMMENT ON COLUMN TH0101_PRACTICE_MNG.VERSION IS 'バージョン';
COMMENT ON COLUMN TH0101_PRACTICE_MNG.RONRI_SAKUJO_FLG IS '論理削除フラグ';
COMMENT ON COLUMN TH0101_PRACTICE_MNG.CREATE_DATE IS '作成日時';
COMMENT ON COLUMN TH0101_PRACTICE_MNG.CREATE_USER_CD IS '作成ユーザコード';
COMMENT ON COLUMN TH0101_PRACTICE_MNG.UPDATE_DATE IS '更新日時';
COMMENT ON COLUMN TH0101_PRACTICE_MNG.UPDATE_USER_CD IS '更新ユーザコード';
