DROP TABLE TH0103_PRACTICE_BIBLIOGRAPHY;

CREATE TABLE TH0103_PRACTICE_BIBLIOGRAPHY (
PRACTICE_MNG_NO CHAR(13 CHAR) NOT NULL, 
BIBLIOGRAPHY_NO　NUMBER(2,0) NOT NULL, 
BIBLIOGRAPHY_NAME VARCHAR2(100 CHAR), 
PUBLISHER  VARCHAR2(20 CHAR), 
VERSION　NUMBER(9,0) NOT NULL, 
RONRI_SAKUJO_FLG CHAR(1 CHAR) NOT NULL, 
CREATE_DATE DATE NOT NULL, 
CREATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
UPDATE_DATE DATE NOT NULL, 
UPDATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
CONSTRAINT TH0103_PRACTICE_BIBLIOGRAPHY_PK PRIMARY KEY (PRACTICE_MNG_NO,BIBLIOGRAPHY_NO)
);

COMMENT ON TABLE TH0103_PRACTICE_BIBLIOGRAPHY IS '参考文献';
COMMENT ON COLUMN TH0103_PRACTICE_BIBLIOGRAPHY.PRACTICE_MNG_NO IS 'サンプル管理番号';
COMMENT ON COLUMN TH0103_PRACTICE_BIBLIOGRAPHY.BIBLIOGRAPHY_NO IS '参考文献番号';
COMMENT ON COLUMN TH0103_PRACTICE_BIBLIOGRAPHY.BIBLIOGRAPHY_NAME IS '文献名';
COMMENT ON COLUMN TH0103_PRACTICE_BIBLIOGRAPHY.PUBLISHER IS '出版社';
COMMENT ON COLUMN TH0103_PRACTICE_BIBLIOGRAPHY.VERSION IS 'バージョン';
COMMENT ON COLUMN TH0103_PRACTICE_BIBLIOGRAPHY.RONRI_SAKUJO_FLG IS '論理削除フラグ';
COMMENT ON COLUMN TH0103_PRACTICE_BIBLIOGRAPHY.CREATE_DATE IS '作成日時';
COMMENT ON COLUMN TH0103_PRACTICE_BIBLIOGRAPHY.CREATE_USER_CD IS '作成ユーザコード';
COMMENT ON COLUMN TH0103_PRACTICE_BIBLIOGRAPHY.UPDATE_DATE IS '更新日時';
COMMENT ON COLUMN TH0103_PRACTICE_BIBLIOGRAPHY.UPDATE_USER_CD IS '更新ユーザコード';
