DROP TABLE TH0104_PRACTICE_WEBSITE;

CREATE TABLE TH0104_PRACTICE_WEBSITE (
PRACTICE_MNG_NO CHAR(13 CHAR) NOT NULL, 
WEBSITE_NO　NUMBER(2,0) NOT NULL, 
WEBSITE_OVERVIEW VARCHAR2(100 CHAR),
WEBSITE_URL VARCHAR2(1000 CHAR),
VERSION　NUMBER(9,0) NOT NULL, 
RONRI_SAKUJO_FLG CHAR(1 CHAR) NOT NULL, 
CREATE_DATE DATE NOT NULL, 
CREATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
UPDATE_DATE DATE NOT NULL, 
UPDATE_USER_CD VARCHAR2(50 CHAR) NOT NULL, 
CONSTRAINT TH0104_PRACTICE_WEBSITE_PK PRIMARY KEY (PRACTICE_MNG_NO,WEBSITE_NO)
);

COMMENT ON TABLE TH0104_PRACTICE_WEBSITE IS '参考サイト';
COMMENT ON COLUMN TH0104_PRACTICE_WEBSITE.PRACTICE_MNG_NO IS 'サンプル番号';
COMMENT ON COLUMN TH0104_PRACTICE_WEBSITE.WEBSITE_NO IS 'サイト番号';
COMMENT ON COLUMN TH0104_PRACTICE_WEBSITE.WEBSITE_OVERVIEW IS 'サイト概要';
COMMENT ON COLUMN TH0104_PRACTICE_WEBSITE.WEBSITE_URL IS 'サイトURL';
COMMENT ON COLUMN TH0104_PRACTICE_WEBSITE.VERSION IS 'バージョン';
COMMENT ON COLUMN TH0104_PRACTICE_WEBSITE.RONRI_SAKUJO_FLG IS '論理削除フラグ';
COMMENT ON COLUMN TH0104_PRACTICE_WEBSITE.CREATE_DATE IS '作成日時';
COMMENT ON COLUMN TH0104_PRACTICE_WEBSITE.CREATE_USER_CD IS '作成ユーザコード';
COMMENT ON COLUMN TH0104_PRACTICE_WEBSITE.UPDATE_DATE IS '更新日時';
COMMENT ON COLUMN TH0104_PRACTICE_WEBSITE.UPDATE_USER_CD IS '更新ユーザコード';
